### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [elye/demo_android_viewmodel_savedstate#1]
I get this:

![image](https://user-images.githubusercontent.com/5357526/73161905-3fd04380-40f5-11ea-9d43-4dd56e6279e1.png)

**Comment by elye** [comment]
This is more like a minor glitch in Android Studio. https://stackoverflow.com/a/53920901/3286489 Nothing to do with this example repo. Close this issue.

**Comment by AndroidDeveloperLB** [comment]
No. It happens only on this project. On others it works fine. 
Why close this issue? It still exists.
I tested on 2 different PCs...

**Comment by elye** [comment]
This doesn't breaks the code from running. Just some Android Studio .idea and .iml related upgrade issue. I'm closing it, as it doesn't break the example code.
Feel free to make a PR to clear and update them if you have time.

**Comment by AndroidDeveloperLB** [comment]
Removing those files has fixed it. Why not provide the repository working this way from the start?

:(

Also, you used `ViewModelProviders.of` which is deprecated. See [here](https://github.com/husaynhakeem/Androidx-SavedState-Playground/issues/3) .  You are supposed to use:

```
ViewModelProvider(fragmentActivity, factory).get(MyViewModel::class.java)
```

I've updated and fixed all of the issues on this repository to make it work. Here's a PR:
https://github.com/elye/demo_android_viewmodel_savedstate/pull/3
