### ISSUE TITLE
Question: Can "MyViewModel" have Application as a property like AndroidViewModel ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [elye/demo_android_viewmodel_savedstate#2]
As the title says..

**Comment by elye** [comment]
This is for filing issue, not for question. Closing this case. My proposal is, in model try to avoid storing any Android specific item.

**Comment by AndroidDeveloperLB** [comment]
Actually, I got it right using this:

```kt
class MyViewModel(application: Application, val state: SavedStateHandle): AndroidViewModel(application)

viewModel = ViewModelProvider(activity!!, SavedStateViewModelFactory(activity!!.application!!, this)).get(MyViewModel::class.java)
```

As for "avoid storing any Android specific item." , why? It is quite often that I need Context, as there are various things on Android that require it.

**Comment by elye** [comment]
It is not a good practice to have Android specific items within the view model, as it makes unit testing (mocking Android specific item) harder

**Comment by AndroidDeveloperLB** [comment]
So how would you access functions that require Context?
